logFilters:
  - code: YN0063
    level: discard
  - code: YN0062
    level: discard
  - code: YN0007
    level: discard
  - code: YN0013
    level: discard
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
